apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: voyager-ssl-1
  namespace: sample-domain1-ns
  annotations:
    ingress.appscode.com/type: 'NodePort'
    ingress.appscode.com/stats: 'true'
    ingress.appscode.com/affinity: 'cookie'
spec:
  tls:
  - secretName: domain1-tls-cert
    hosts:
    - domain1.org
  rules:
  - host: domain1.org 
    http:
      nodePort: '30305'
      paths:
      - backend:
          serviceName: domain1-admin-server
          servicePort: '7001'
