# Copyright (c) 2018, 2020, Oracle Corporation and/or its affiliates.

resources:
    JDBCSystemResource:
        mysqlDS:
            JdbcResource:
                JDBCDriverParams:
                    URL: 'jdbc:mysql://@@ENV:DOMAIN_UID@@-mysql:3306/mysql'
                    Properties:
                        user:
                            Value: '@@SECRET:@@ENV:DOMAIN_UID@@-mysql-secret:root-user@@'
