apiVersion: v1
entries:
  weblogic-operator:
  - created: 2019-02-27T13:42:00.663635122-05:00
    description: Helm chart for configuring the WebLogic operator.
    digest: 155ebf001218919a6b478bbf82068301736cfdaa1be6bb86ac49fb91a859be28
    name: weblogic-operator
    urls:
    - https://oracle.github.io/weblogic-kubernetes-operator/charts/weblogic-operator-2.1.tgz
    version: "2.1"
generated: 2019-02-27T13:42:00.658848305-05:00
