# Copyright 2017, 2018, Oracle Corporation and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
# This is an sample domain resource which has domainHome in image but domain logs in a PV.
#

apiVersion: "weblogic.oracle/v3alpha1"
kind: Domain
metadata:
  name: domain2
  namespace: test1 
  labels:
    weblogic.resourceVersion: domain-v2
    weblogic.domainUID: domain2
spec:
  domainHome: /u01/oracle/user-projects/domains/domain2 
  domainHomeInImage: true
  image: domain2-image
  imagePullPolicy: "IfNotPresent"
  logHomeEnabled: true
  logHome: /domain_logs/domain2/
  webLogicCredentialsSecret: 
    name: domain2-weblogic-credentials
  includeServerOutInPodLog: true
  serverStartPolicy: "IF_NEEDED"
  replicas: 2
  serverPod:
    volumes:
    - name: weblogic-domain-storage-volume
      persistentVolumeClaim:
        claimName: weblogic-domain-logs-pvc
    volumeMounts:
    - mountPath: /domain_logs
      name: weblogic-domain-storage-volume
  adminServer:
    adminService:
      channels:
      - channelName: default
        nodePort: 30703
      - channelName: T3Channel
