# Copyright 2019, Oracle Corporation and/or its affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.

apiVersion: "weblogic.oracle/v2"
kind: Domain
metadata:
  name: domain1-uid
  namespace: sample-domain1-ns
  labels:
    weblogic.resourceVersion: domain-v2
    weblogic.domainUID: domain1-uid
spec:
  image: store/oracle/weblogic:12.2.1.3
  imagePullPolicy: IfNotPresent
  webLogicCredentialsSecret: 
    name: domain1-uid-weblogic-credentials
  domainHomeInImage: false
  logHomeEnabled: true
  logHome: /shared/logs/domain1-uid
  includeServerOutInPodLog: true
  serverPod:
    env:
    - name: JAVA_OPTIONS
      value: "-Dweblogic.StdoutDebugEnabled=false"
    - name: USER_MEM_ARGS
      value: "-Xms64m -Xmx256m "
    volumes:
    - name: domain-namespace-storage-volume
      persistentVolumeClaim:
        claimName: sample-domain1-ns-pvc
    volumeMounts:
    - mountPath: /shared
      name: domain-namespace-storage-volume
  adminServer:
    adminService:
      channels:
      - channelName: default
        nodePort: 30701
      - channelName: T3Channel
  replicas: 1
