# Copyright 2019, Oracle Corporation and/or its affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.

apiVersion: v1
kind: Pod
metadata:
  name: domain1-uid-create-pod
  namespace: sample-domain1-ns
  labels:
    weblogic.resourceVersion: domain-v2
    weblogic.domainUID: domain1-uid
spec:
  restartPolicy: Never
  containers:
    - name: create-domain-home
      image: store/oracle/weblogic:12.2.1.3
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /shared
          name: domain-namespace-storage-volume
        - mountPath: /weblogic-credentials
          name: weblogic-credentials-volume
      command: ["bash", "-c"]
      args:
        - echo starting;
          DEF_DIR='/u01/domain1-def';
          export DOMAIN_HOME='/shared/domains/domain1-uid';
          while [[ ! -d ${DEF_DIR} ]]; do
            sleep 5;
          done;
          cd ${DEF_DIR};
          mkdir -p ${DOMAIN_HOME};
          cp -R wlsdeploy ${DOMAIN_HOME};
          wlst.sh -skipWLSModuleScanning ${DEF_DIR}/model/model.py;
          find ${DOMAIN_HOME} -type f;
          cat ${DOMAIN_HOME}/config/config.xml;
          echo done;
          exit 0;
  volumes:
    - name: domain-namespace-storage-volume
      persistentVolumeClaim:
        claimName: sample-domain1-ns-pvc
    - name: weblogic-credentials-volume
      secret:
        secretName: domain1-uid-weblogic-credentials
