apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: default-vs
spec:
  hosts:
  - "*"
  gateways:
  - default-gateway
  http:
  - match:
    - uri:
        prefix: /console
    route:
    - destination:
        host: domain1-admin-server-external.ns1.svc.cluster.local
        port:
          number: 7001
  - route:
    - destination:
        host: domain1-cluster-cluster-1.ns1.svc.cluster.local
        port:
          number: 31111
      weight: 50
    - destination:
        host: domain2-cluster-cluster-1.ns2.svc.cluster.local
        port:
          number: 31111
      weight: 50

        
        

