apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  namespace: sample-domain1-ns
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
 rules:
 -  http:
     paths:
     - path: /(.+)
       backend:
         serviceName: domain1-cluster-cluster-1
         servicePort: 9001
