# Copyright 2019, Oracle Corporation and/or its affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: domain1-uid-pv
  labels:
    weblogic.resourceVersion: domain-v2
    weblogic.domainUID: domain1-uid
spec:
  storageClassName: domain1-uid-storage-class
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /scratch/k8s-dir/storage/domains/domain1-uid

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: domain1-uid-pvc
  namespace: sample-domain1-ns
  labels:
    weblogic.resourceVersion: domain-v2
    weblogic.domainUID: domain1-uid
spec:
  storageClassName: domain1-uid-storage-class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
